### ISSUE TITLE
requirements.txt是手工维护的？

### ISSUE THREAD

**Issue by imom0** [pengyuan/snowflake#1]
这样其他人没法**方便的**搭建开发环境，用virtualenv吧，`pip freeze > requirements.txt`。

**Comment by pengyuan** [comment]
其实我的生产环境没有多版本的需求。
所以本地开发可以virtualenv一个虚拟环境，然后pip install -r requirements.txt。（“#”注释掉的不会安装）也很方便的~

会积极考虑使用virtualenv。

**Comment by imom0** [comment]
ee7479f2#diff-4 文件改过了，之前的不行。

**Comment by kidlj** [comment]
请问使用 virtualenv 怎样跑起来？在 virtualenv 环境下安装包都成功了，但是运行 `python manage.py runserver` 或者 `python manage makemigrations` 的时候报错：

```python
ImportError: Could not import settings 'mysite.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named mysite.settings
```

谢谢。
